CREATE TABLE OutputTable
(	"RCD_ID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
   "CRT_TS" VARCHAR2(32 BYTE) NOT NULL ENABLE,
   "ALR_TY_CD" VARCHAR2(32 BYTE) NOT NULL ENABLE,
   "PUBL_NM" VARCHAR2(32 BYTE) NOT NULL ENABLE,
   "TPC" VARCHAR2(32 BYTE) NOT NULL ENABLE,
   "ACTN_STNG" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
  CONSTRAINT "PK_AEOT" PRIMARY KEY ("RCD_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);


