CREATE TABLE WSO2_SP_OUTPUT_TABLE
(
  "MSG_ID"     VARCHAR2(128 BYTE) DEFAULT NULL,
  "TPC"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "CRT_TS"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "MQ_SRC_NM"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "ALR_TY_CD" VARCHAR2(128 BYTE) DEFAULT NULL,
  "ACTN_STNG"   VARCHAR2(2000 BYTE),
 CONSTRAINT "PK_OutputTable" PRIMARY KEY ("MSG_ID", "TPC")
);


CREATE TABLE WSO2_SP_SCHEDULED_ALERTS
(
  "MSG_ID"     VARCHAR2(128 BYTE) DEFAULT NULL,
  "TPC"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "TEMPLATE_TYPE"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "CUST_ID"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "ALR_TY_CD"    VARCHAR2(128 BYTE) DEFAULT NULL,
  "EACT_CD" VARCHAR2(128 BYTE) DEFAULT NULL,
  "MQ_SRC_NM" VARCHAR2(128 BYTE) DEFAULT NULL,
  "MSG_REC_NM" VARCHAR2(128 BYTE) DEFAULT NULL,
  "CREATED_TIME"   VARCHAR2(1000 BYTE),
  "SHEDULED_TIME" VARCHAR2(1000 BYTE),
  CONSTRAINT "PK_SCHEDULED_ALERTS" PRIMARY KEY ("MSG_ID", "TPC", "TEMPLATE_TYPE", "CUST_ID",  "EACT_CD", "SHEDULED_TIME", "MQ_SRC_NM", "MSG_REC_NM" )
);

CREATE TABLE WSO2_SP_ALERT_SUMMARY
("MSG_ID"     VARCHAR2(128 BYTE) DEFAULT NULL,
  "TPC"     VARCHAR2(128 BYTE) DEFAULT NULL,
  "TEMPLATE_TYPE"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "CUST_ID"      VARCHAR2(128 BYTE) DEFAULT NULL,
  "ALR_TY_CD"      VARCHAR2(200 BYTE) DEFAULT NULL,
  "EACT_CD"      VARCHAR2(200 BYTE) DEFAULT NULL,
  "EML_ADDR" VARCHAR2(200 BYTE) DEFAULT NULL,
  "CREATED_TIME"  DATE,
  CONSTRAINT "ALERT_SUMMARY" PRIMARY KEY ("MSG_ID", "TPC", "TEMPLATE_TYPE",  "CUST_ID","ALR_TY_CD","EACT_CD" ,"EML_ADDR" )
);

CREATE TABLE WSO2_SP_ALERT_MESSAGE_BODY(MSG_ID VARCHAR2(128 BYTE),
  "TPC"      VARCHAR2(128 BYTE) DEFAULT NULL,
  TEMPLATE_TYPE VARCHAR2(128 BYTE), SUBJECT VARCHAR2(128 BYTE), FROM_ADDR VARCHAR2(128 BYTE), BODY VARCHAR2(4000 BYTE),  PRIMARY KEY(MSG_ID, TPC, TEMPLATE_TYPE));
